[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/*"
#     Access-Control-Allow-Origin = "*"
#     # Multi-key header rules are expressed with multi-line strings.
#     cache-control = '''
#       max-age=31536000,
#       must-revalidate,
#       public'''

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/public/page-data/"

#     # Multi-key header rules are expressed with multi-line strings.
#     cache-control = '''
#       max-age=0,
#       must-revalidate,
#       public'''

# [[headers]]
#   # Define which paths this specific [[headers]] block will cover.
#   for = "/static/"
# 
#     # Multi-key header rules are expressed with multi-line strings.
#     cache-control = '''
#       max-age=31536000,
#       must-revalidate,
#       public,
#       immutable'''
# [[plugins]]
#   package = "netlify-plugin-checklinks"
#     [plugins.inputs]
#     # An array of glob patterns for pages on your site
#     # Recursive traversal will start from these
#     entryPoints = [
#     "*.html",
#     ]
#     # You can mark some check as skipped, which will block checklinks
#     # from ever attempting to execute them.
#     # skipPatterns is an array of strings you can match against failing reports
#     skipPatterns = ["*.inline.svg"]

# [[plugins]]
#   package = "netlify-plugin-gatsby-cache"