backend:
  name: git-gateway
  repo: SEALAB-Software/international-website
  branch: master

media_folder: static/img
public_folder: /img

logo_url: /img/sealab-blue.svg
editor:
  preview: false
display_url:  https://sealab-com.netlify.com

collections:

  - name: "simple-pages"
    label: "Rene tekst sider"
    folder: "src/pages/"
    create: true
    description: "Dette er enkle tekst sider, som vi kan lage flere av. Inneholder kun tittel og en tekst-editor."
    filter: {field: "templateKey", value: "simple-page"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
      - {label: "Tittel", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Overskrift", name: "heading", widget: "string", hint: "Dette er overskriften man først ser på toppen av siden."}
      - {label: "Innhold", name: "body", widget: "markdown"}
  
  
  - name: "settings"
    label: "Navigasjon & Footer"
    description: "Her kan du endre på lenker i navigasjon og footer. Hvis du ønsker å legge til, fjerne eller fikse på rekkefølge, har du kommet til rett sted."
    files: 
      - file: "src/pages/innstillinger/navbar.md"
        label: "Navigasjon"
        name: "navbar"
        fields: 
          - label: "Lenker"
            name: "menuLinks"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - {label: Lenke, name: link, widget: string, hint: "Hvis den har dropdown, så legg kun til: #", default: "#"}
              - label: Dropdown
                name: dropdown
                widget: list
                hint: "Hvis tom, så vises det ingen dropdown eller pil."
                fields:
                  - {label: Overskrift, name: title, widget: string}
                  - {label: Lenke, name: link, widget: string}
      - file: "src/pages/innstillinger/footer.md"
        label: "Footer"
        name: "footer"
        fields: 
          - label: "1 - Hovedsider"
            name: "mainNavigation"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - {label: Lenke, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "2 - Apper"
            name: "softwareNavigation"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - {label: Lenke, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "3 - Hardware"
            name: "hardwareNavigation"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - {label: Lenke, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}          
          - label: "4 - Om"
            name: "secondaryNavigation"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - {label: Lenke, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "Bedriftskontorer"
            name: "companyOffices"
            widget: "list"
            fields: 
              - {label: Overskrift, name: title, widget: string}
              - label: Addresselinjer
                name: addressItems
                widget: list
                hint: "Separer ny linje med komma: adresselinje 1, adresselinje 2, postnummer, poststed"
          - label: "Call to action"
            name: "callToAction"
            widget: "object"
            fields:
              - {label: "Tittel", name: "title", widget: "string"}
              - {label: "Kort beskrivelse", name: "description", widget: "string"}
              - {label: "Knappetekst", name: "buttonText", widget: "string"}
              - {label: "URL - CALL TO ACTION", name: "buttonPath", widget: "string"}



  - name: "pages"
    label: "Vanlige sider"
    files:
      - file: "src/pages/index.md"
        label: "Forside"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: SEO Beskrivelse, name: seoDescription, widget: text, hint: "Important - Make a overall description"}
          - {label: Heading, name: heading, widget: string}
          - {label: "Hero image", name: "featuredimage", widget: image }
          - label: Facts
            widget: list
            name: items
            fields:
              - {label: Heading, name: heading, widget: string, hint: "Try to keep it to one word"}
              - {label: Description, name: description, widget: text}
            - label: Centered section
              widget: object
              name: centeredSection
              fields:
                - {label: "Background image", name: "bgimage", widget: image }
                - {label: Subheading, name: subheading, widget: string}
                - {label: Heading, name: heading, widget: string}
                - {label: Description, name: description, widget: text}
                - label: Button
                  widget: object
                  name: button
                  fields:
                    - {label: "Button text", name: text, widget: string, hint: "Keep it short"}
                    - {label: "Button path", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}


          

