backend:
  name: git-gateway
  repo: SEALAB-Software/international-website
  branch: master

media_folder: static/img
public_folder: /img

logo_url: /img/sealab-blue.svg
editor:
  preview: false
display_url:  https://sealab-com.netlify.com

collections:

#### SIMPLE PAGES ####

  - name: "simple-pages"
    label: "Simple text pages"
    folder: "src/pages/"
    create: true
    description: "Dette er enkle tekst sider, som vi kan lage flere av. Inneholder kun tittel og en tekst-editor."
    filter: {field: "templateKey", value: "simple-page"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
      - {label: "Title", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Description", name: "heading", widget: "string", hint: "Dette er overskriften man først ser på toppen av siden."}
      - {label: "Content", name: "body", widget: "markdown"}

#### SOLUTION PAGES TEMPLATE SECONDARY ####
  - name: "solution-page-secondary"
    label: "Industries pages - Short"
    folder: "src/pages/solutions/"
    create: true
    description: "This is a solution page. Also known as industries and markets."
    filter: {field: "templateKey", value: "solution-page-secondary"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "solution-page-secondary"}
      - {label: "Title", name: "title", widget: "string", hint: "Title on the tab and SEO title."}
      - {label: "SEO Description", name: "seoDescription", widget: "text", hint: "SEO is important for search engines."}
      - {label: "Heading", name: "heading", widget: "string", hint: "This is shown with the section image"}
      - {label: "Description", name: "description", widget: "text", hint: "This is shown with the section image"}
      - {label: "Image", name: "featuredimage", widget: "image", hint: "First section image."}
      - label: "Sections"
        hint: Create as many you like
        name: splitSections
        required: false
        widget: list
        fields:
            - {label: "Subheading", name: "subheading", widget: "string", required: false }
            - {label: "Heading", name: "heading", widget: "string", requred: false}
            - {label: "Content on the right", name: "content", widget: "markdown", }
            - {label: "Image", name: "featuredimage", widget: "image", hint: "Image", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false,}

#### SOLUTION PAGES TEMPLATE Primary ####
  - name: "solution-page-primary"
    label: "Industries pages - Long"
    folder: "src/pages/solutions/"
    create: true
    description: "This is a solution page. Also known as industries and markets."
    filter: {field: "templateKey", value: "solution-page-primary"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "solution-page-primary"}
      - {label: "Title", name: "title", widget: "string", hint: "Title on the tab and SEO title."}
      - {label: "SEO Description", name: "seoDescription", widget: "text", hint: "SEO is important for search engines."}
      - {label: "Heading", name: "heading", widget: "string", hint: "This is shown with the section image"}
      - {label: "Description", name: "description", widget: "text", hint: "This is shown with the section image"}
      - {label: "Image", name: "featuredimage", widget: "image", hint: "First section image."}
      - label: "Sections"
        hint: Create as many you like
        name: splitSections
        widget: list
        fields:
            - {label: "Subheading", name: "subheading", widget: "string", required: false }
            - {label: "Heading", name: "heading", widget: "string", requred: false}
            - {label: "Content on the right", name: "content", widget: "markdown", }
            - {label: "Image", name: "featuredimage", widget: "image", hint: "Image", required: false}
      - label: "Large image section"
        name: imageSection
        widget: object
        required: false
        fields:
            - {label: "Image", name: "featuredimage", widget: "image", hint: "Image", required: false}
            - {label: "Content - left", name: "left", widget: "markdown", required: false}
            - {label: "Content - right", name: "right", widget: "markdown", required: false }
      - label: "Splitted section bottom of page"
        name: splitSection
        widget: object
        required: false
        fields:
            - {label: "Heading", name: "heading", widget: "string", required: false}
            - {label: "Content - left", name: "left", widget: "markdown", required: false }
            - {label: "Content - right", name: "right", widget: "markdown", required: false }
            

  
#### ABOUT PAGE TEMPLATE 1 ####

  - name: "about-page-template-primary"
    label: "About Pages"
    folder: "src/pages/about/"
    create: true
    description: "This is a about page template."
    filter: {field: "templateKey", value: "about-page-template-primary"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page-template-primary"}
      - {label: "Title", name: "title", widget: "string", hint: "Title on the tab and SEO title."}
      - {label: "Heading", name: "heading", widget: "string", hint: "This is the title you see on the top of a page."}
      - {label: "Description", name: "description", widget: "text", hint: "Text."}
      - {label: "SEO Description", name: "seoDescription", widget: "text", hint: "SEO is important for search engines."}
      - {label: "Image", name: "featuredimage", widget: "image", hint: "Image to use on the page."}
      - {label: "Content", name: "body", widget: "markdown"}

#### PRODUCT PAGE TEMPLATE 1 ####
  - name: "product-pages-primary"
    label: "Product pages"
    folder: "src/pages/products/"
    create: true
    description: "This is the primary product page template."
    filter: {field: "templateKey", value: "product-page-primary"}
    identifier_field: products-primary
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page-primary"}
      - {label: "Title", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Heading", name: "heading", widget: "string", hint: "Dette er overskriften man først ser på toppen av siden."}
      - {label: "SEO Description", name: "seoDescription", widget: "text", hint: "SEO is important for search engines like Google"}
      - {label: "Description", name: "description", widget: "text"}
      - label: Comparison
        name: item1vsitem2
        required: false
        widget: object
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - label: "Item 1"
            name: item1
            widget: object
            fields:
              - {label: "Comparison list", name: "items", widget: "list"}
          - label: "Item 2"
            name: item2
            widget: object
            fields:
              - {label: "Comparison list", name: "items", widget: "list"}

      - {label: "First section image", name: "featuredimageSecondary", widget: image }
      - {label: "First section content", name: "body", widget: "markdown"}

      - {label: "Centered text", name: "centeredText", widget: "markdown"}

      - label: "Last section"
        widget: object
        name: thirdSection
        fields:
          - {label: "Left image", name: "featuredimage", widget: image }
          - {label: "Right content", name: "content", widget: "markdown"}

#### PROJECT PAGE TEMPLATE 1 ####
  - name: "project-page-primary"
    label: "Project Pages 1"
    folder: "src/pages/projects/"
    create: true
    description: "This is the primary project page template."
    filter: {field: "templateKey", value: "project-page-primary"}
    identifier_field: projects-primary
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-page-primary"}
      - {label: "Title", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Heading", name: "heading", widget: "string", hint: "Dette er overskriften man først ser på toppen av siden."}
      - {label: "SEO Description", name: "seoDescription", widget: "text", hint: "SEO is important for search engines like Google"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured image", name: "featuredImage", widget: image }
      - {label: "Featured image caption", name: "featuredImageCaption", widget: "text", required: false }
      - label: "Key factors"
        name: "keyFactors"
        widget: "object"
        fields:
          - {label: "Key features heading", name: "heading", widget: "string", hint: "Dette er overskriften i key factors-boksen"}
          - label: "Key features"
            name: "factorItems"
            widget: list
            fields:
              - {label: "Factor", name: "primaryInfo", widget: "text" }
              - {label: "Factor description", name: "description", widget: "text" }
      - {label: "Content", name: "body", widget: "markdown"}
      - label: "Partners"
        name: "partners"
        widget: "object"
        fields:
          - {label: "Partners heading", name: "heading", widget: "string" }
          - label: "Partners list"
            name: "partnerItems"
            widget: list
            fields:
              - {label: "Partner logo", name: "icon", widget: image }
              - {label: "Partner description", name: "description", widget: "text", required: false }


  - name: "settings"
    label: "Navigation & Footer"
    description: "Her kan du endre på lenker i navigasjon og footer. Hvis du ønsker å legge til, fjerne eller fikse på rekkefølge, har du kommet til rett sted."
    files: 
      - file: "src/pages/innstillinger/navbar.md"
        label: "Navigation"
        name: "navbar"
        fields: 
          - label: "Links"
            name: "menuPaths"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Hvis den har dropdown, så legg kun til: #", default: "#"}
              - label: Dropdown
                name: dropdown
                widget: list
                hint: "Hvis tom, så vises det ingen dropdown eller pil."
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Link, name: path, widget: string}
      - file: "src/pages/innstillinger/footer.md"
        label: "Footer"
        name: "footer"
        fields: 
          - label: "Main navigation"
            name: "mainNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "Products"
            name: "secondaryNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "Projects"
            name: "thirdNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}          
          - label: "About"
            name: "fourthNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "Company offices"
            name: "companyOffices"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Addresselinjer
                name: addressItems
                widget: list
                hint: "Separer ny linje med komma: adresselinje 1, adresselinje 2, postnummer, poststed"
          - label: "Call to action"
            name: "callToAction"
            widget: "object"
            fields:
              - {label: "Tittel", name: "title", widget: "string"}
              - {label: "Short description", name: "description", widget: "string"}
              - {label: "Button text", name: "buttonText", widget: "string"}
              - {label: "URL - CALL TO ACTION", name: "buttonPath", widget: "string"}


#### STATIC PAGES (FRONT PAGE for example) ####
  - name: "pages"
    label: "Regular pages"
    files:
      - file: "src/about/index.md"
        label: "Front page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: SEO Description, name: seoDescription, widget: text, hint: "Important - Make a overall description"}
          - {label: Heading, name: heading, widget: string}
          - {label: "Hero image", name: "bgimage", widget: image }
          - label: Facts
            widget: list
            name: items
            fields:
              - {label: Heading, name: heading, widget: string, hint: "Try to keep it to one word"}
              - {label: Description, name: description, widget: text}
          - label: Centered section
            widget: object
            name: centeredSection
            fields:
              - {label: "Background image", name: "bgimage", widget: image }
              - {label: Subheading, name: subheading, widget: string}
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Button
                widget: object
                name: button
                fields:
                  - {label: "Button text", name: text, widget: string, hint: "Keep it short"}
                  - {label: "Button path", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}

          - label: Product section
            widget: object
            name: productSection
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: "Product image", name: "featuredimage", widget: image }
              - {label: "Product background image", name: "featuredimageBackground", widget: image, required: false }
              - {label: Description, name: description, widget: text}


          - label: Quotes section
            widget: list
            name: quotes
            required: false
            fields:
              - {label: "Author name", name: authorName, widget: string, required: false}
              - {label: "Author position", name: authorPosition, widget: string, required: false}
              - {label: "Author image", name: "authorImage", widget: image, required: false}
              - {label: "Quote text", name: quoteText, widget: text, required: false}

          - label: Solutions
            widget: object
            name: itemsSection
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Button
                widget: object
                name: button
                fields:
                  - {label: "Button text", name: text, widget: string, hint: "Keep it short"}
                  - {label: "Button path", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}
              - label: "Solution items"
                widget: list
                name: items
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: "Solution image", name: "featuredimage", widget: image }
                  - {label: "Path to page", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}
          - label: Inspirational section
            name: splitSection
            widget: object
            fields: 
              - {label: "Large image", name: "bgimage", widget: image }
          - {label: "Content next to inspirational image", name: "body", widget: "markdown"}

      - file: "src/pages/social-responsibility.md"
        label: "Social responsibility"
        name: "about-social-responsibility"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-social-responsibility"}
          - {label: Title, name: title, widget: string}
          - {label: SEO Description, name: seoDescription, widget: text, hint: "Important - Make a overall description"}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: text, required: false}
          - label: "UN Responsibility images"
            name: featuredImages
            widget: list
            field: {label: Image, name: image, widget: image}
          - label: "UN Sustainable"
            name: splitSection
            required: false
            widget: object
            fields:
                - {label: "Content - left", name: "left", widget: "markdown", required: false }
                - {label: "Content - right", name: "right", widget: "markdown", required: false }
          - label: "Three columns"
            name: "three-col-section"
            required: false
            widget: list
            fields:
                - {label: "Content - left", name: "description", widget: "markdown", required: false }
                - {label: Icon, name: icon, widget: image, required: false }
          - label: "Sustainability"
            name: splitSection2
            required: false
            widget: object
            fields:
                - {label: "Content - left", name: "left", widget: "markdown", required: false }
                - {label: "Image - right", name: "right", widget: "image", required: false }
          - label: "Responsibilities"
            name: "responsibilities"
            required: false
            widget: list
            fields:
                - {label: "Heading --->", name: "description", widget: "string", required: false }
                - {label: "Content", name: "description", widget: "markdown", required: false }
          - label: "ISO"
            name: splitSection3
            required: false
            widget: object
            fields:
                - {label: "Content - left", name: "left", widget: "markdown", required: false }
                - {label: "Image - right", name: "right", widget: "image", required: false }