backend:
  name: git-gateway
  repo: SEALAB-Software/international-website
  branch: master

media_folder: static/img
public_folder: /img

logo_url: /img/sealab-blue.svg
editor:
  preview: false
display_url:  https://sealab-com.netlify.com

collections:

  - name: "simple-pages"
    label: "Simple text pages"
    folder: "src/pages/"
    create: true
    description: "Dette er enkle tekst sider, som vi kan lage flere av. Inneholder kun tittel og en tekst-editor."
    filter: {field: "templateKey", value: "simple-page"}
    identifier_field: name
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "simple-page"}
      - {label: "Title", name: "title", widget: "string", hint: "Tittel på fanen og SEO tittel"}
      - {label: "Description", name: "heading", widget: "string", hint: "Dette er overskriften man først ser på toppen av siden."}
      - {label: "Content", name: "body", widget: "markdown"}
  
  
  - name: "settings"
    label: "Navigation & Footer"
    description: "Her kan du endre på lenker i navigasjon og footer. Hvis du ønsker å legge til, fjerne eller fikse på rekkefølge, har du kommet til rett sted."
    files: 
      - file: "src/pages/innstillinger/navbar.md"
        label: "Navigasjon"
        name: "navbar"
        fields: 
          - label: "Links"
            name: "menuLinks"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: link, widget: string, hint: "Hvis den har dropdown, så legg kun til: #", default: "#"}
              - label: Dropdown
                name: dropdown
                widget: list
                hint: "Hvis tom, så vises det ingen dropdown eller pil."
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Link, name: link, widget: string}
      - file: "src/pages/innstillinger/footer.md"
        label: "Footer"
        name: "footer"
        fields: 
          - label: "1 - Hovedsider"
            name: "mainNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "2 - Apper"
            name: "softwareNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "3 - Hardware"
            name: "hardwareNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}          
          - label: "4 - Om"
            name: "secondaryNavigation"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Link, name: path, widget: string, hint: "Dette er linken. Husk å test denne. Dette vil være f.eks: /navn-på-siden"}
          - label: "Bedriftskontorer"
            name: "companyOffices"
            widget: "list"
            fields: 
              - {label: Title, name: title, widget: string}
              - label: Addresselinjer
                name: addressItems
                widget: list
                hint: "Separer ny linje med komma: adresselinje 1, adresselinje 2, postnummer, poststed"
          - label: "Call to action"
            name: "callToAction"
            widget: "object"
            fields:
              - {label: "Tittel", name: "title", widget: "string"}
              - {label: "Short description", name: "description", widget: "string"}
              - {label: "Button text", name: "buttonText", widget: "string"}
              - {label: "URL - CALL TO ACTION", name: "buttonPath", widget: "string"}



  - name: "pages"
    label: "Regular pages"
    files:
      - file: "src/pages/index.md"
        label: "Front page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: SEO Description, name: seoDescription, widget: text, hint: "Important - Make a overall description"}
          - {label: Heading, name: heading, widget: string}
          - {label: "Hero image", name: "bgimage", widget: image }
          - label: Facts
            widget: list
            name: items
            fields:
              - {label: Heading, name: heading, widget: string, hint: "Try to keep it to one word"}
              - {label: Description, name: description, widget: text}
          - label: Centered section
            widget: object
            name: centeredSection
            fields:
              - {label: "Background image", name: "bgimage", widget: image }
              - {label: Subheading, name: subheading, widget: string}
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: text}
              - label: Button
                widget: object
                name: button
                fields:
                  - {label: "Button text", name: text, widget: string, hint: "Keep it short"}
                  - {label: "Button path", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}

          - label: Product section
            widget: object
            name: productSection
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: "Product image", name: "featuredimage", widget: image }
              - {label: "Product background image", name: "featuredimageBackground", widget: image, required: false }
              - {label: Description, name: description, widget: text}


          - label: Quotes section
            widget: list
            name: quotes
            fields:
              - {label: "Author name", name: authorName, widget: string}
              - {label: "Author position", name: authorPosition, widget: string}
              - {label: "Author image", name: "authorImage", widget: image, required: false}
              - {label: "Quote text", name: quoteText, widget: text}

          - label: Solutions
            widget: object
            name: itemsSection
            fields:
              - {label: Heading, name: heading, widget: string}
              - label: Button
                widget: object
                name: button
                fields:
                  - {label: "Button text", name: text, widget: string, hint: "Keep it short"}
                  - {label: "Button path", name: path, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}
              - label: "Solution items"
                widget: list
                name: items
                fields:
                  - {label: Heading, name: heading, widget: string}
                  - {label: "Solution image", name: "featuredimage", widget: image }
                  - {label: "Path to page", name: heading, widget: string, hint: "Last part of url. Example: /products/edge-intelligence"}
          - label: Inspirational section
            name: splitSection
            widget: object
            fields: 
              - {label: "Large image", name: "bgimage", widget: image }
          - {label: "Content next to inspirational image", name: "body", widget: "markdown"}

        

